# Generated by Django 3.2.3 on 2021-06-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='healthPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('total_price', models.FloatField(max_length=100, verbose_name='total price')),
                ('discount_price', models.FloatField(max_length=100, verbose_name='discount price')),
                ('package_includes', models.CharField(max_length=500, verbose_name='package includes')),
                ('package_description', models.TextField(max_length=500, verbose_name='package description')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(blank=True, max_length=100)),
                ('licence_no', models.CharField(blank=True, max_length=100)),
                ('exp_date', models.CharField(blank=True, max_length=100)),
                ('provience_no', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('rural_municipality', models.CharField(blank=True, max_length=100)),
                ('ward_no', models.CharField(blank=True, max_length=100)),
                ('tole_area_apmnt', models.CharField(blank=True, max_length=100)),
                ('telephone_no', models.CharField(blank=True, max_length=100)),
                ('org_type', models.CharField(blank=True, max_length=100)),
                ('pan_vat_no', models.CharField(blank=True, max_length=100)),
                ('your_role', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('founder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platelet_count', models.CharField(blank=True, max_length=100, null=True, verbose_name='palate count')),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='catefory name')),
                ('test_cost', models.FloatField(blank=True, max_length=1000, null=True, verbose_name='test cost')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.ImageField(default='profile.jpg', upload_to='lab-images/cover-images', verbose_name='cover image')),
                ('youtube', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lab.imagealbum')),
                ('lab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('bio', models.TextField(verbose_name='Biograph')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pics', to='lab.imagealbum')),
            ],
        ),
    ]
