# Generated by Django 3.2.3 on 2021-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(blank=True, max_length=100)),
                ('licence_no', models.CharField(blank=True, max_length=100)),
                ('exp_date', models.CharField(blank=True, max_length=100)),
                ('provience_no', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('rural_municipality', models.CharField(blank=True, max_length=100)),
                ('ward_no', models.CharField(blank=True, max_length=100)),
                ('tole_area_apmnt', models.CharField(blank=True, max_length=100)),
                ('telephone_no', models.CharField(blank=True, max_length=100)),
                ('org_type', models.CharField(blank=True, max_length=100)),
                ('pan_vat_no', models.CharField(blank=True, max_length=100)),
                ('your_role', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
