# Generated by Django 3.2.3 on 2021-06-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('total_price', models.FloatField(max_length=100, verbose_name='total price')),
                ('discount_price', models.FloatField(max_length=100, verbose_name='discount price')),
                ('package_includes', models.CharField(max_length=500, verbose_name='package includes')),
                ('package_description', models.TextField(max_length=500, verbose_name='package description')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('bio', models.TextField(verbose_name='Biograph')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pics', to='lab.imagealbum')),
            ],
        ),
    ]
