# Generated by Django 3.2.3 on 2021-06-02 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='founder',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
