# Generated by Django 3.2.3 on 2021-06-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='is_active',
            new_name='is_verified',
        ),
    ]
