# Generated by Django 3.2.3 on 2021-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_lab_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
