# Generated by Django 3.2.3 on 2021-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
