# Generated by Django 3.2.3 on 2021-06-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_lab_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
