# Generated by Django 3.2.3 on 2021-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platelet_count', models.CharField(blank=True, max_length=100, null=True, verbose_name='palate count')),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='catefory name')),
                ('test_cost', models.FloatField(blank=True, max_length=1000, null=True, verbose_name='test cost')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='labprofile',
            name='cover_img',
            field=models.ImageField(default='profile.jpg', upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='gallery_image0',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='gallery_img1',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='gallery_img2',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='gallery_img3',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='gallery_img4',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='logo_img',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='lab-images/cover-images', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
